accounts/urls.py
from django.conf.urls import url
from accounts import views
# SET THE NAMESPACE!
app_name = 'accounts'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

shopping/urls.py
from django.urls import path,re_path
from django.conf.urls import include
from shopping import views 

urlpatterns = [
    path('create-product/',views.create_product,name="create_product"),
    path('',views.list_product,name="list_product"),
    re_path('product-details/(?P<pk>.*)/$',views.view_product,name="view_product"),
    re_path('update-product/(?P<pk>.*)/$',views.update_product,name="update_product"),
]

shopping_cart/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls import include,url
from accounts import views as accounts
from shopping import views as shopping

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(("accounts.urls","accounts"))),
    url(r'^logout/$', accounts.user_logout, name='logout'),
    path('', shopping.homepage, name='homepage'),
    path('shopping/', include(("shopping.urls","shopping"))),

    re_path('media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path('static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_FILE_ROOT}),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class UserProfile(models.Model):
	user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
	address=models.TextField(blank=True,null=True)
	phone=models.CharField(max_length=30,blank=True)
	date_joined=models.DateTimeField(auto_now_add=True)
	updated_on=models.DateTimeField(auto_now=True)
	is_creator=models.BooleanField(default=False)

	class Meta:
		db_table = 'UserProfile'
		verbose_name = _('user profile')
		verbose_name_plural = _('user profiles')
		ordering = ['-date_joined']

	def __str__(self):
		return self.user.username

shopping/models.py
from django.db import models
from decimal import Decimal
from django.core.validators import MinValueValidator
# Create your models here.


class Product(models.Model):
	name = models.CharField(max_length=128)
	price = models.DecimalField(default=0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
	quantity = models.CharField(max_length=128)
	image = models.FileField()
	status = models.BooleanField(default=True)

	def __str__(self):
		return self.name

accounts/forms.py
from django import forms
from accounts.models import UserProfile
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileForm(forms.ModelForm):
     class Meta():
         model = UserProfile
         fields = ('address','phone')

shopping/forms.py
from .models import Product
from django import forms
# from django.forms.widgets import TextInput, Textarea
# from django.utils.translation import ugettext_lazy as _


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, get_object_or_404
from .forms import UserProfileForm,UserForm
from .models import UserProfile
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def register(request):
	registered = False
	if request.method == 'POST':
		# in here we can pass request.POST in form using with 'data' variable or without 'data' variable
		user_form = UserForm(data=request.POST)
		user_profile_form = UserProfileForm(request.POST)
		if user_form.is_valid() and user_profile_form.is_valid():
			user = user_form.save()
			user_profile = user_profile_form.save(commit=False)
			user_profile.user = user
			if 'address' in request.POST:
				address = request.POST['address']
			else:
				address = ''
			if 'phone' in request.POST:
				phone = request.POST['phone']
			else:
				return HttpResponse("Phone is required!")
			user_profile.address = address
			user_profile.phone = phone
			user_profile.save()
			registered = True
			return HttpResponseRedirect(reverse('homepage'))
		else:
			return HttpResponse(user_form.errors,user_profile_form.errors)
	else:
		user_form = UserForm()
		user_profile_form = UserProfileForm()
		context ={
			'user_profile_form':user_profile_form,
			'user_form':user_form,
			'registered':registered
		}
		return render(request,'accounts/register.html',context)

def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		if username == None or password == None:
			return HttpResponse("Please provide both username and password")
		user = get_object_or_404(User.objects.filter(username=username,password=password))
		# user = authenticate(username=username,password=password)
		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('homepage'))
			else:
				return HttpResponse("Your account was inactive")
		else:
			return HttpResponse('invalid login details given')
	else:
		context={}
		return render(request,'accounts/user_login.html',context)

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('homepage'))

shopping/views.py
from django.shortcuts import render,get_object_or_404
from .models import Product
from .forms import ProductForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse


def homepage(request):
    return render(request,'homepage.html',{})

@login_required
def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")
        else:
            return HttpResponse(form.errors)
    else:
        form = ProductForm()
        context = {
            "form":form,
            "heading":"Create Product"
        }
        return render(request, "product/create_product.html", context)

@login_required
def list_product(request):
    products = Product.objects.filter(status=True)
    context = {
        "products":products,
        "heading":"List Products"
    }
    return render(request,"product/products.html",context)

@login_required
def view_product(request,pk):
    product = get_object_or_404(Product.objects.filter(pk=pk))
    context = {
        "product":product,
        "heading":"View Product"
    }
    return render(request,"product/product.html",context)

@login_required
def update_product(request,pk):
    instance = get_object_or_404(Product.objects.filter(pk=pk))
    if request.method == 'POST':
        form = ProductForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")

    else:
        form = ProductForm(instance=instance)
        context = {
            "form" : form,
            "heading":"Edit Product"
        }
        return render(request,"product/create_product.html",context)

# @login_required
# def delete_product(request,pk):
#     product = get_object_or_404(Product.objects.filter(pk=pk))
#     product.delete()
#     return HttpResponseRedirect("/")

templates/accounts/register.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
      <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
          <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ user_profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/accounts/user_login.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
      	<h1>Login here :</h1>
		<form method="post" action="{% url 'accounts:user_login' %}">
      		{% csrf_token %}
          	<label for="username">Username:</label>
          	<input type="text" name="username" placeholder="Username">
			<label for="password">Password:</label>
          	<input type="password" name="password" placeholder="Password">
			<input type="submit" name="" value="Login">
		</form>
	</div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-link" href="{% url 'homepage' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'shopping:list_product' %}">Shopping Product</a></li>
          <li><a class="navbar-link" href="{% url 'accounts:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'accounts:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/homepage.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Shopping Cart</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/product/create_product.html
<!DOCTYPE html>
<html>
<head>
	<title>{{heading}}</title>
	<style type="text/css">
		.fg-line{
			width: 60%;
		    text-align: center;
		    margin: 0 auto 2%;
		}
		.fg-label{
			color: #6d5353;
	    font-weight: bold;
	    margin-right: 2%;
		}
		.button{
            margin-top: 3%;
            width: 100px;
            padding: 5px;
            color: #fdfdfd;
            text-decoration: none;
            font-weight: bold;
            background: #e66a6a;
		}
	</style>
</head>
<body>
	<div style="width: 70%;
    margin: 0 auto;
    text-align: center;
    background: #dfe3e4;
    padding: 2%;">
    <h2 style="text-align: center;color: #6b6464;">Create Product</h2>
	    <form method="POST" enctype="multipart/form-data">
	        {% csrf_token %}
	        <div class="fg-line">
				<label class="fg-label">Name</label>
				{{ form.name }}
				{% if form.name.errors %}
		            <span class="error">{{ form.name.errors.as_text }}</span>
		        {% endif %}
			</div>
			<div class="fg-line">
				<label class="fg-label">Price</label>
				{{ form.price }}
				{% if form.price.errors %}
		            <span class="error">{{ form.price.errors.as_text }}</span>
		        {% endif %}
			</div>
			<div class="fg-line">
				<label class="fg-label">Qty</label>
				{{ form.quantity }}
				{% if form.quantity.errors %}
		            <span class="error">{{ form.quantity.errors.as_text }}</span>
		        {% endif %}
			</div>
			<div class="fg-line">
				<label class="fg-label">Image</label>
				{{ form.image }}
				{% if form.image.errors %}
		            <span class="error">{{ form.image.errors.as_text }}</span>
		        {% endif %}
			</div>
			<div class="fg-line">
				<label class="fg-label">Status</label>
				{{ form.status }}
				{% if form.status.errors %}
		            <span class="error">{{ form.status.errors.as_text }}</span>
		        {% endif %}
			</div>
	        <input type="submit" value="Submit" class="button" />
	    </form>
	</div>
</body>
</html>

templates/product/product.html
<!DOCTYPE html>
<html>
<head>
	<title>{{heading}}</title>
    <style type="text/css">
        .lgi-heading{
            font-size: 20px;
            font-weight: bold;
            color: grey;
            margin: 8px 0 4px;
        }
        .lgi-text{
            font-size: 16px;
        }
        .button{
            margin-top: 3%;
            width: 100px;
            padding: 5px;
            color: #fdfdfd;
            text-decoration: none;
            font-weight: bold;
            background: #e66a6a;
        }
    </style>
</head>
<body>
    {% if product %}
    <div style="width: 70%;
    margin: 0 auto; text-align: center;background: #e1f4f7;padding: 1%;">
        <div style="text-align: center;">
            <h2>Product Info <small></small></h2>
        </div>

        <div>
            <div>
                <div>
                    <div>
                        <div class="lgi-heading">Product Name</div>
                        <small class="lgi-text">{{product.name}}</small>
                    </div>
                </div>

                <div class="list-group-item media">
                    <div class="media-body">
                        <div class="lgi-heading">Price</div>
                        <small class="lgi-text">{{ product.price }}</small>
                    </div>
                </div>
                <div class="list-group-item media">
                    <div class="media-body">
                        <div class="lgi-heading">Qty</div>
                        <small class="lgi-text">{{ product.quantity }}</small>
                    </div>
                </div>
                <div class="list-group-item media">
                    <div class="media-body" style="width: 35%; margin: 0 auto;">
                        <div class="lgi-heading">Image</div>
                        <div><img src="{{product.image.url}}" alt="{{product.name}}" style="width: 100%;height: 100%;" /></div>
                    </div>
                </div>
                <button class="button"><a href="{% url 'shopping:update_product' pk=product.pk %}" style="color: white;
    text-decoration: none;">Edit</a></button>
            </div>
        </div>
        {% else %}
        <p style="color: red;font-size: 24px;font-weight: bold;text-align: center;">No Contents! So Please Add</p>
        {% endif %}
    </div>
</body>
</html>

templates/product/products.html
<!DOCTYPE html>
<html>
<head>
	<title>{{heading}}</title>
    <style type="text/css">
        .button{
            margin-top: 3%;
            width: 60px;
            padding: 5px;
            color: #fdfdfd;
            text-decoration: none;
            font-weight: bold;
            background: #e66a6a;
            display: inline-block;
        }
    </style>
</head>
<body>
    <nav>
        {% if user.is_authenticated %}
        <p><a href="{% url 'logout' %}">Logout</a></p>
        {% endif %}
    </nav>
    {% if products %}
    <div style="width: 80%;
    margin: 0 auto;">
        <table style="width: 100%;">
            <thead style="text-align: center;">
                <tr>
                    <th data-column-id="id" data-type="numeric">ID</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Qty</th>
                    <th>Image</th>
                    <th>Status</th>
                    <th data-column-id="action">Action</th>
                </tr>
            </thead>
            <tbody style="text-align: center;">
                {% for product in products %}
                <tr>
                    <td>
                        <a href="{% url 'shopping:view_product' pk=product.pk %}">{{product.pk}}</a>
                    </td>
                    <td>
                        <a href="{% url 'shopping:view_product' pk=product.pk %}">{{product.name}}</a>
                    </td>
                    <td>{{product.price}}</td>
                    <td>{{product.quantity}}</td>
                    <td style="width: 100px;height: 100px;"><img src="{{product.image.url}}" alt="{{product.name}}" style="width:100%;"/></td>
                    <td>{{product.status}}</td>
                    <td>
                        <a href="{% url 'shopping:update_product' pk=product.pk %}" class="button">Edit</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
</body>
</html>